### ISSUE TITLE
Add meta/og/twitter tags to head

### ISSUE THREAD

**Issue by cameronmaske** [cameronmaske/cameronmaske.com-v2#2]
- [x] description
- [x] twitter:site [main]
- [x] twitter:creator [main]
- [x] twitter:title
- [x] twitter:description
- [x] twitter:card
- [x] twitter:image
- [x] property=og:title
- [x] property=og:type 
- [x] property=og:url
- [x] property=og:image
- [x] property=og:description
- [ ] property="article:published_time"
- [ ] property=article:modified_time
